name: Extra
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  vulns:
    name: Vulnerability scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          stable: 'false' # Keep this line to be able to use rc and beta version of Go (ex: 1.18.0-rc.1).
          go-version: 1.19.0-rc.2
      - name: Run go list
        run: go list -json -m all > go.list
      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@v1.0.2
